###
GET http://localhost:5050/user

###
GET http://localhost:5050/user/3

###
DELETE http://localhost:5050/user/5

###
POST http://localhost:5050/user
Content-Type: application/json

{
    "email":"vendedor@leo.com",
    "password":"123456",
    "typeProfile":2
}

###
POST http://localhost:5050/login
Content-Type: application/json

{
    "email":"leo3@leo.com",
    "password":"123456"
}

###
PATCH http://localhost:5050/user/2
Content-Type: application/json

{
    "firstname":"leo aaa",
    "lastname":"merida aaa"
}

